# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tyler Brown
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://tylerbrown.cc
baseurl:          /

author:
  name:           'Tyler Brown'
  url:            https://twitter.com/tylerb0422

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tylerjamesbrown7/tylerjamesbrown7.github.io
